@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome reverse

autonumber

Alice -> Server: Authentication Request
Server --> Alice: Authentication Response

Alice -> Server: grep/awk/sed expression, stdin
Alice <-- Server: stdout, stderr
@enduml